version: '3'

services:
  app:
    image: pipl/dummy-app:1.0.0
    build:
      context: dummy-app
      dockerfile: Dockerfile
    networks:
    esnet:  
 
  filebeat:
    hostname: filebeat
    image: pipl/filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:   
     - "/var/lib/docker/containers:/usr/share/Pipl/data:ro"
     - "/var/run/docker.sock:/var/run/docker.sock"
    links:
       - logstash
    networks:
    esnet:   
   

  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
    esnet:  
  

  logstash: 
    hostname: logstash 
    image: pipl/logstash:1.0.0
    build:
      context: logstash
      dockerfile: Dockerfile
    ports:
      - 5044:5044
    networks:
    esnet:  
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
   
      
  elasticsearch:
    hostname: elasticsearch
    image: pipl/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.master=true
      - node.ingest=true
      - node.data=false
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=3
    volumes:
      - esdata1:/usr/share/elasticsearch/data  
      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
    esnet:  
      
  elasticsearch2:
    hostname: elasticsearch
    image: pipl/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.master=true
      - node.ingest=true
      - node.data=false
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=3
    volumes:
      - esdata2:/usr/share/elasticsearch/data  
    ulimits:
      memlock:
        soft: -1
        hard: -1    
    networks:
    esnet:    

  elasticsearch3:
    hostname: elasticsearch
    image: pipl/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.master=true
      - node.ingest=false
      - node.data=false
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=3
    volumes:
      - esdata3:/usr/share/elasticsearch/data        
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks:
    esnet:    
      
  elasticsearch4:
    hostname: elasticsearch
    image: pipl/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.master=false
      - node.ingest=false
      - node.data=true
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=3
    volumes:
      - esdata4:/usr/share/elasticsearch/data       
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks:
    esnet:    
        
 
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local  

networks:
    esnet:
